# Generated by Django 2.2.10 on 2020-05-21 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator',
            name='bio',
            field=models.CharField(default='edit - e.g Teacher at Gauteng School', max_length=300),
        ),
        migrations.AddField(
            model_name='creator',
            name='profile',
            field=models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='profile_photo_folder', verbose_name='p_p'),
        ),
    ]
