# Generated by Django 2.2.10 on 2020-05-22 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0002_auto_20200521_0532'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='creator',
            name='social-media-url',
            field=models.URLField(default='www.example.com'),
        ),
    ]
