# Generated by Django 2.2.10 on 2020-05-22 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0003_auto_20200522_0221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creator',
            name='profile',
            field=models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='profile_photo_folder', verbose_name='profile_photo'),
        ),
    ]
