# Generated by Django 2.2.10 on 2020-05-20 15:40

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0001_initial'),
        ('creator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='audio_folder/', verbose_name='audio_file')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='video_folder/', verbose_name='vid_file')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='header')),
                ('description', models.TextField()),
                ('lesson_header_image', models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='lesson_pic_folder/', verbose_name='lessonpics')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('content_format', models.CharField(choices=[('Video', 'Video'), ('Audio', 'Audio'), ('Text', 'Text')], default='Text', max_length=6)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('publish', models.BooleanField(default=False)),
                ('published', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='creator.Creator')),
                ('category', models.ManyToManyField(blank=True, null=True, related_name='lesson_category', to='blog.Category')),
                ('content_audios', models.ManyToManyField(blank=True, related_name='content_audioss', to='lesson.Video')),
                ('content_videos', models.ManyToManyField(blank=True, related_name='content_vids', to='lesson.Video')),
                ('keywords', models.ManyToManyField(related_name='lesson_keywords', related_query_name='lesson_keywords', to='blog.Keywords', verbose_name='tagss')),
            ],
        ),
    ]
