# Generated by Django 2.2.10 on 2020-06-10 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='content_audios',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='content_videos',
        ),
        migrations.AddField(
            model_name='lesson',
            name='content_audio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='content_audioss', to='lesson.Video'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='content_video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='content_vids', to='lesson.Video'),
        ),
    ]
